# Generated by Django 4.0.1 on 2022-01-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basestr',
            name='name',
        ),
        migrations.AddField(
            model_name='status',
            name='name',
            field=models.CharField(default='New', max_length=100),
        ),
        migrations.AddField(
            model_name='type',
            name='name',
            field=models.CharField(default='Task', max_length=100),
        ),
    ]
