# Generated by Django 4.0.1 on 2022-01-15 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_issue_status_alter_issue_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='issues', through='webapp.IssueType', to='webapp.Type'),
        ),
        migrations.AddField(
            model_name='issuetype',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ishue_types', to='webapp.issue', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='issuetype',
            name='type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_issues', to='webapp.type', verbose_name='Тип'),
        ),
    ]
