# Generated by Django 4.0.1 on 2022-01-16 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_issuetype_issue_types_issuetype_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuetype',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_types', to='webapp.issue', verbose_name='Задача'),
        ),
    ]
