# Generated by Django 4.0.1 on 2022-01-16 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_issuetype_issue'),
    ]

    operations = [
        migrations.RenameField('Issue', 'type', 'type_old')
    ]
