# Generated by Django 4.0.1 on 2022-01-16 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_rename_type_old_issue_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='type',
            new_name='type_old',
        ),
    ]
