# Generated by Django 4.0.1 on 2022-01-16 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20220116_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='type_old',
            new_name='type',
        ),
    ]
