# Generated by Django 4.0.1 on 2022-01-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_remove_issue_types_issue_typesdfg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='typesdfg',
        ),
        migrations.AddField(
            model_name='issue',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='issues', through='webapp.IssueType', to='webapp.Type'),
        ),
    ]
