# Generated by Django 4.0.1 on 2022-01-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_rename_typeserf_issue_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='types',
            new_name='type_name',
        ),
    ]
