# Generated by Django 4.0.1 on 2022-01-16 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_rename_types_issue_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuetype',
            name='type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_issues', to='webapp.type', verbose_name='Тип'),
        ),
    ]
