# Generated by Django 4.0.1 on 2022-01-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_alter_issuetype_type_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='type_name',
            new_name='type_names',
        ),
    ]
