# Generated by Django 4.0.1 on 2022-01-17 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_rename_type_name_issue_type_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='webapp.type'),
        ),
    ]
