# Generated by Django 4.0.1 on 2022-01-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_remove_issue_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='type_names',
            new_name='type_names_old',
        ),
    ]
