# Generated by Django 4.0.1 on 2022-01-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_rename_type_names_issue_type_names_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='type_names_old',
            field=models.ManyToManyField(blank=True, related_name='issues_old', through='webapp.IssueType', to='webapp.Type'),
        ),
    ]
