# Generated by Django 4.0.1 on 2022-01-17 10:45

from django.db import migrations


def transfer_tags(apps, schema_editor):
    Issue = apps.get_model('webapp.Issue')
    for issue in Issue.objects.all():
        issue.type_names.set(issue.type_names_old.all())


def rollback_transfer(apps, schema_editor):
    Issue = apps.get_model('webapp.Issue')
    for issue in Issue.objects.all():
        issue.type_names_old.set(issue.type_names.all())


class Migration(migrations.Migration):
    dependencies = [
        ('webapp', '0027_issue_type_names'),
    ]

    operations = [
        migrations.RunPython(transfer_tags, rollback_transfer)
    ]
