# Generated by Django 4.0.1 on 2022-01-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_auto_20220117_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='type_names_old',
        ),
        migrations.DeleteModel(
            name='IssueType',
        ),
    ]
