# Generated by Django 4.0.1 on 2022-01-18 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_remove_issue_type_names_old_delete_issuetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='summary',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5, 'it should not be less then 5 character')]),
        ),
    ]
