# Generated by Django 4.0.1 on 2022-01-29 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='projects',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='webapp.project'),
            preserve_default=False,
        ),
    ]
