# Generated by Django 4.0.1 on 2022-01-30 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_issue_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='projects',
            new_name='project',
        ),
    ]
