# Generated by Django 4.0.1 on 2022-01-31 11:44

from django.db import migrations, models
import webapp.validatiors


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0036_alter_issue_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, validators=[webapp.validatiors.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='issue',
            name='summary',
            field=models.CharField(max_length=200, validators=[webapp.validatiors.MinLengthValidator(5, 'it should not be less then 5 character')]),
        ),
    ]
