# Generated by Django 4.0.1 on 2022-02-20 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0040_issue_author_project_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_manage_users', 'Может управлять пользавателями')]},
        ),
    ]
